const mongoose=require('mongoose')
const eventSchema=mongoose.Schema({
    name:{
        type:String
    },
    startDate:{
        type:String
    },
    endDate:{
        type:String
    },
    registeredPlayer:[{
        type:String,
        ref:'User'
    }],
    bracket:[{
        bracketName:{
            type:String
        },
        bracket_type:{
            type:String
        },
        progression:{
            type:Boolean
        },
        noOfProgressingUser:{
            type:String
        },
        progressionBracket:{
            type:String
        },
        bracketOrder:{
            type:Number
        },
        players:[{
            type:String,
            ref:'User'
        }],
        matches:{
            type:String,
            ref:'Matches'
        }
    }],
})
const Event=mongoose.model('Event',eventSchema)
module.exports=Event